.editorconfig, .stylelintrc, config.js, gulpfile.js, package-lock.json, package.json, src/assets/sass/protocol/base/elements/_lists.scss, src/assets/sass/site/prism.scss
Kind of a mess at the moment with the watch task inherited from Drizzle, but we can tidy it up later.
This also renames the package. A step closer to dedrizzling.
=> Add stylelint

src/assets/sass/demos/type-scale.scss, src/assets/sass/docs/site.scss, src/assets/sass/protocol/base/elements/_document.scss, src/assets/sass/protocol/base/elements/_typography.scss, src/assets/sass/protocol/components/_article.scss, src/assets/sass/protocol/components/_sidebar-menu.scss, src/assets/sass/protocol/includes/mixins/_typography.scss, src/pages/demos/type-scale.hbs, src/pages/fundamentals/typography.hbs, src/templates/drizzle/nav.hbs
This updates our type scale naming scheme and introduces a few new sizes.
https://demo2--mozilla-protocol.netlify.com/fundamentals/typography.html
https://demo2--mozilla-protocol.netlify.com/demos/type-scale.html
=> Revise type scale, rename sizes

src/assets/sass/docs/site.scss, src/assets/sass/protocol/base/_elements.scss, src/assets/sass/protocol/base/elements/_forms.scss, src/patterns/atoms/forms/checkboxes.hbs, src/patterns/atoms/forms/errors.hbs, src/patterns/atoms/forms/field-note.hbs, src/patterns/atoms/forms/fieldset.hbs, src/patterns/atoms/forms/input-placeholder.hbs, src/patterns/atoms/forms/radio-buttons.hbs, src/patterns/atoms/forms/required-field.hbs, src/patterns/atoms/forms/select.hbs, src/patterns/atoms/forms/text-input.hbs, src/patterns/atoms/forms/textarea.hbs
https://demo2--mozilla-protocol.netlify.com/patterns/atoms/forms.html
=> Add basic form elements

README.md, docs/README.md
Took a stab at de-Drizzling our README.md.
=> Tidy README.md files (Fixes #121)

Jenkinsfile, bin/build.sh, bin/irc-notify.sh, package.json
For https://github.com/mozmeao/infra/issues/830
s3 buckets for stage and prod have been created and test pushes have been completed in https://ci.us-west.moz.works/view/protocol/job/protocol/job/jenkins-s3/4/console and https://ci.us-west.moz.works/view/protocol/job/protocol/job/jenkins-s3/5/console
=> Jenkins s3

src/patterns/atoms/links/text.hbs
Added advise not to use internal nofollow on links
=> Added Seo advice on links

CHANGELOG.md, src/assets/sass/protocol/components/_billboard.scss, src/pages/demos/billboard.hbs
Fixes https://github.com/mozilla/protocol/issues/138
=> Adjust bottom margin for billboard components (Fixes #138)

CHANGELOG.md, src/assets/sass/protocol/components/_card.scss
Fixes https://github.com/mozilla/protocol/issues/136
=> Remove redundant .mzp-c-card-small-cta styles (Fixes #136)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_typography.scss
=> Add Firefox global theme class (Fixes #169)

CHANGELOG.md, src/assets/sass/protocol/components/_button.scss, src/assets/sass/protocol/components/_download-button.scss, src/assets/sass/protocol/components/_newsletter-form.scss, src/assets/sass/protocol/protocol-extra.scss, src/patterns/atoms/buttons/basic.hbs, src/patterns/atoms/buttons/download.hbs, src/patterns/molecules/download-button/download-button.hbs
- Updates our regular button style to black.
- Adds basic download button component (with privacy policy link).
- Fixes constrast issues with the download button.
=> Update button styles (Fixes #167)

CHANGELOG.md, src/assets/sass/protocol/components/_billboard.scss, src/patterns/organisms/billboard/billboard.hbs
=> Remove the image link from the billboard molecule (Fixes #143)

CHANGELOG.md, src/pages/demos/card-layout.hbs
For reference: https://github.com/mozilla/bedrock/issues/5865#issuecomment-402071643
=> Update card layout demo title to "6 Card Layout"

CHANGELOG.md, package-lock.json, package.json, src/assets/sass/demos/call-out.scss, src/assets/sass/protocol/components/_call-out.scss, src/assets/sass/protocol/components/_newsletter-form.scss, src/assets/sass/protocol/includes/_mixins.scss, src/assets/sass/protocol/includes/_variables.scss, src/assets/sass/protocol/includes/mixins/_at2x.scss, src/assets/sass/protocol/protocol-extra.scss, src/pages/demos/call-out-compact.hbs, src/pages/demos/call-out.hbs, src/patterns/organisms/call-out/call-out-compact.hbs, src/patterns/organisms/call-out/call-out.hbs, src/patterns/organisms/call-out/collection.yml
- Adds Call Out component and compact variation.
Demo:
- https://mozilla-protocol.netlify.com/patterns/organisms/call-out.html
- https://mozilla-protocol.netlify.com/demos/call-out.html
- https://mozilla-protocol.netlify.com/demos/call-out-compact.html
=> Add Call Out component (Fixes #153)

CHANGELOG.md, gulp/config.js, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
Fixes https://github.com/mozilla/protocol/issues/174
=> Include @mozilla-protocol/tokens source files in build (Fixes #172)

CHANGELOG.md, src/assets/sass/protocol/components/_billboard.scss
=> Billboard text overflows container with long strings (Fixes #180)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_links.scss, src/assets/sass/protocol/components/_card.scss, src/patterns/molecules/card/medium-card.hbs, src/patterns/molecules/card/small-card.hbs
=> Add inline CTA to card

CHANGELOG.md, src/assets/sass/protocol/components/_billboard.scss, src/patterns/organisms/billboard/billboard.hbs
=> Billboard alignment broken in Safari (Fixes #207)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_document.scss
A couple of quick fixes to make our fonts easier to read. Resolves #219
=> Font Optimization

CHANGELOG.md, src/assets/sass/protocol/components/_card.scss, src/patterns/molecules/card/extra-small-card.hbs, src/patterns/molecules/card/large-card.hbs, src/patterns/molecules/card/medium-card.hbs, src/patterns/molecules/card/small-card.hbs
Fixes #227 
I verified this fix by looking at the card layout demo page, and also by changing these two values directly on the www.mozilla.org home page using dev tools.
=> Fix card layout issues at medium viewport sizes (Fixes #227)

CHANGELOG.md, src/assets/sass/protocol/base/_elements.scss, src/assets/sass/protocol/base/elements/_quotes.scss, src/patterns/atoms/typographic/quotes.hbs
Styles `blockquote` element per example provided in issue #234
=> Fix #234: Add blockquote

CHANGELOG.md, docs/README.md
=> Document deployment process (Fixes #171)

CHANGELOG.md, src/assets/js/protocol/protocol-menu.js
=> Fixed menu component focusout bug (Fixes #247)

.eslintrc.js, CHANGELOG.md, src/assets/js/protocol/protocol-lang-switcher.js, src/assets/js/protocol/protocol-menu.js, src/assets/js/protocol/protocol-modal.js, src/assets/js/protocol/protocol-navigation.js, src/pages/demos/navigation.hbs, src/patterns/molecules/language-switcher/language-switcher.hbs, src/patterns/molecules/menu/menu.hbs, src/patterns/organisms/modal/modal.hbs, src/patterns/organisms/navigation/navigation.hbs, tests/unit/protocol-lang-switcher.js, tests/unit/protocol-menu.js, tests/unit/protocol-navigation.js
=> Update JS namespace from Mozilla to Mzp (Fixes #253)

CHANGELOG.md, src/assets/sass/protocol/components/_button.scss, src/patterns/atoms/buttons/primary.hbs, src/patterns/atoms/buttons/secondary.hbs
=> Primary buttons should use a solid background color on hover (Fixes #264)

CHANGELOG.md, docs/README.md, src/assets/sass/protocol/components/_call-out.scss, src/pages/demos/hero.hbs, src/patterns/organisms/hero/hero.hbs
Fixes #268 
- Also removes a few stray classes from the hero component.
=> Fix download button positioning in call out component (Fixes #268)

CHANGELOG.md, src/assets/sass/protocol/components/_footer.scss, src/assets/sass/protocol/components/_language-switcher.scss, src/patterns/molecules/language-switcher/language-switcher.hbs, src/patterns/organisms/footer/footer.hbs
=> Update Language Selector to include optional link to language selection page (Fixes #259)

CHANGELOG.md, gulp/tasks/sass-compile.js, package-lock.json, package.json
=> Remove autoprefixer to ensure consistency using pre-compiled CSS (Fixes #119)

CHANGELOG.md, src/assets/sass/protocol/components/_billboard.scss
=> Billboard overflowing text in IE 10 (Fixes #276)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_links.scss, src/assets/sass/protocol/components/_card.scss, src/assets/sass/protocol/includes/_mixins.scss, src/pages/demos/call-out-compact.hbs, src/pages/demos/call-out.hbs, src/patterns/organisms/call-out/call-out-compact.hbs, src/patterns/organisms/call-out/call-out.hbs, src/patterns/organisms/hero/hero.hbs
https://github.com/mozilla/protocol/issues/280
=> Convert CTA links to blue

CHANGELOG.md, src/assets/sass/protocol/base/elements/_sections.scss
Super basic but better than unstyled.
=> Add base <hr> styles (#296)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_lists.scss, src/patterns/atoms/typographic/lists.hbs
=> Define basic dl styles (#295)

docs/README.md
Wording tweaks to deployment docs.
=> Update deployment docs

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
=> Bump version to 5.0.0

CHANGELOG.md, src/assets/sass/protocol/components/_article.scss
Decrease size of article h3 and h4s
Fix #293
See it in action on the[ article demo](http://localhost:3000/demos/article.html) page.
=> Decrease size of article h3 and h4s #293

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
=> Publish version 6.0.0

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
=> Update to 7.0.0.

.travis.yml
=> Fix Travis xvfb error

CHANGELOG.md, src/assets/sass/protocol/includes/mixins/_typography.scss
#389 
Watch the "Display MD" heading on this page: https://protocol.mozilla.org/fundamentals/typography.html#styles
=> Text display mixins use consistant breakpoint (#389)

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
=> Publish 7.0.1

CHANGELOG.md, src/assets/package/README.md, src/assets/package/package.json
=> Publish 7.0.2

CHANGELOG.md, src/assets/sass/protocol/components/_sidebar-menu.scss
Fix #407
The mobile side menu can be found on [the article demo page](https://protocol.mozilla.org/demos/article.html) at small screen sizes
=> Increase contrast on sidebar mobile menu #407

src/patterns/molecules/card/extra-small-card.hbs, src/patterns/molecules/card/large-card.hbs, src/patterns/molecules/card/medium-card.hbs, src/patterns/molecules/card/small-card.hbs
See #201
You can check my math if you like :P
=> Add example height and widths to card component docs (#201)

CHANGELOG.md, docs/README.md, package-lock.json, src/assets/package/README.md, src/assets/package/package.json
=> Publish 8.0.0

package-lock.json, package.json
Leftover from #466. Update what version of Protocol we're using.
=> Update root to use Protocol 8.0.0

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
Publish a new version of Protocol.
=> Publish 9.0.0

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
Bug fix release for https://github.com/mozilla/protocol/pull/496
~- [ ] I have documented this change in the design system.~
=> Bump version to 9.0.1

CHANGELOG.md, package-lock.json, package.json
=> Update @mozilla-protocol/assets to 3.0.1 (#509)

CHANGELOG.md, src/assets/sass/protocol/components/_emphasis-box.scss, src/patterns/molecules/emphasis-box/medium-emphasis-box.hbs
Add a link to a related GitHub issue if applicable.
Enter helpful notes for whoever code reviews this change.
=> fixes #489

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
=> Publish 10.0.0

CHANGELOG.md, src/assets/sass/protocol/components/_zap.scss
Fix #520
I'm not sure how to test this.
=> Fix zap import #520

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
=> Publish 10.0.1

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
Version bump to 11.0.1 to land two small bug fixes for notification bars.
=> Publish 11.0.1

CHANGELOG.md, src/assets/sass/protocol/components/_notification-bar.scss
Fixes #549 - use border-box
Fix image replacement bug
Add focus styles
Tweak spacing
#549
=> Notification bar updates

CHANGELOG.md, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/base/elements/_reset.scss, src/assets/sass/protocol/base/elements/_typography.scss, src/assets/sass/protocol/includes/forms/_lib.scss
Adds form label styling to match spec in #430. 
Also adds styles for legend and fieldset. Legends are kind of like labels, if you think about it.
#430
http://localhost:3000/patterns/atoms/forms.html
http://localhost:3000/demos/newsletter.html
=> Update form label styles (#430)

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
=> Publish 11.0.2

CHANGELOG.md, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/includes/_mixins.scss, src/assets/sass/protocol/includes/forms/_lib.scss, src/assets/sass/protocol/includes/mixins/_images.scss
Updates default styling for select boxes.
Fix #435
http://localhost:3000/patterns/atoms/forms.html
=> Add styled select drop downs (#435)

CHANGELOG.md, src/assets/sass/docs/site.scss, src/assets/sass/protocol/components/_button.scss, src/assets/sass/protocol/includes/forms/_lib.scss, src/pages/demos/emphasis-box.hbs, src/patterns/atoms/buttons/disabled.hbs, src/patterns/atoms/buttons/neutral-dark.hbs, src/patterns/atoms/buttons/neutral.hbs, src/patterns/atoms/buttons/overview.hbs, src/patterns/atoms/buttons/primary-dark.hbs, src/patterns/atoms/buttons/primary.hbs, src/patterns/atoms/buttons/product-secondary-dark.hbs, src/patterns/atoms/buttons/product-secondary.hbs, src/patterns/atoms/buttons/product.hbs, src/patterns/atoms/buttons/secondary-dark.hbs, src/patterns/atoms/buttons/secondary.hbs, src/patterns/atoms/buttons/sizes.hbs, src/patterns/atoms/lists/inline-lists.hbs, src/patterns/molecules/download-button/download-button-secondary.hbs, src/patterns/organisms/navigation/navigation.hbs
Updates button styles.
Fix #429 
http://localhost:3000/patterns/atoms/buttons.html
https://demo1--mozilla-protocol.netlify.com/patterns/atoms/buttons.html
=> Updated button styles (#429)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/base/elements/_reset.scss, src/assets/sass/protocol/includes/mixins/_images.scss, src/pages/demos/newsletter.hbs, src/patterns/atoms/forms/errors.hbs, src/patterns/atoms/forms/other-input.hbs, src/patterns/organisms/newsletter/newsletter.hbs
Add styled text inputs
Fix #430
http://localhost:3000/patterns/atoms/forms.html
=> Add styled text inputs (#430)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/base/elements/_reset.scss
The forms PRs that have recently merged have come from a much larger branch. As part of teasing those changes apart and then rebasing them back together a few lines of duplicate code have crept in. This PR remove those.
I've also moved the utility classes to the end of the forms file without changing any of the declarations.
Part of #508
http://localhost:3000/patterns/atoms/forms.html
=> Form SCSS cleanup

CHANGELOG.md, package-lock.json, package.json
Update @mozilla-protocol/tokens to 5.0.5
=> Update @mozilla-protocol/tokens to 5.0.5

CHANGELOG.md, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/components/_button.scss, src/assets/sass/protocol/components/forms/_choice.scss, src/assets/sass/protocol/includes/forms/_lib.scss, src/assets/sass/protocol/protocol-extra.scss, src/patterns/molecules/forms/collection.yml, src/patterns/molecules/forms/custom-checks.hbs, src/patterns/molecules/forms/fields/choice.hbs
Collectively this component is called "choices".
Fix #439 
This should be rigorously tested in various browsers and operating systems.
I'm open to suggestions about how to improve the documentation.
This commit has some classes in the custom-checks.hbs file that do not have any accompanying CSS in this PR. `form-set` and `form-label` will be added in a follow up PR.
http://localhost:3000/patterns/molecules/forms.html
=> Styled radio buttons and checkboxes

CHANGELOG.md, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/components/_language-switcher.scss
Fix bug with new select box and footer language select
See #584
http://localhost:3000/demos/footer.html
=> Fix bug with new select box and footer language select (#584)

.gitignore, gulpfile.js/config.js, gulpfile.js/tasks/build.js, gulpfile.js/tasks/drizzle.js, gulpfile.js/tasks/generate-icon-data.js, package-lock.json, src/assets/sass/docs/site.scss, src/pages/fundamentals/icons.hbs
Adds an Icon preview page for assets from the protocol-assets repo
=> Icons page

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
Bumps version to 12.0.0 (at last!)
=> Publish 12.0.0

src/patterns/molecules/card/large-card.hbs
Fixes typo and math error in card docs.
None.
Check my math?
=> Typo in card docs

CHANGELOG.md, src/assets/sass/protocol/includes/_mixins.scss
Fix #618
http://localhost:3000/demos/footer.html
=> Set text align on image replacement mixin Fix #618

CHANGELOG.md, src/assets/sass/protocol/includes/forms/_lib.scss
Decrease min-width of form fields.
Fix #607
- Rebase on #611 before testing.
- http://localhost:3000/demos/forms/long.html
=> Decrease min-width of form fields.

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
=> Bump version to 12.0.1

src/pages/demos/card-picto-layout.hbs
I only fixed a small typo error
=> fixed small error

CHANGELOG.md, src/assets/js/protocol/protocol-sticky-promo.js, src/assets/sass/protocol/base/includes/_animations.scss, src/assets/sass/protocol/components/_sticky-promo.scss, src/assets/sass/protocol/protocol-extra.scss, src/patterns/molecules/sticky-promo/sticky-promo.hbs
Adds new sticky promo card component.
#603
=> Add sticky promo component (#603)

src/pages/demos/forms/choices.hbs, src/patterns/atoms/forms/checkboxes.hbs, src/patterns/atoms/forms/radio-buttons.hbs, src/patterns/molecules/forms/custom-checks.hbs
Tidy up form docs. Moved most of the choices stuff to its own demo. Added links to the choices demo in a few places.
http://localhost:3000/patterns/molecules/forms.html#custom-checkboxes-and-radio-buttons
http://localhost:3000/demos/forms/choices.html
=> Tidy up form docs

README.md, src/pages/index.hbs
https://github.com/mozilla/protocol/issues/634
=> Update getting started info (Fixes #634)

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
Updates to 12.1.0. I'm considering this is a feature release since it adds the new sticky promo component.
=> Bump version to 12.1.0

README.md, src/assets/sass/docs/site.scss, src/pages/docs/contributing.md, src/pages/docs/index.hbs, src/pages/index.hbs, src/templates/drizzle/nav.hbs
Our guide to contributing is/was very minimal and not actually all that helpful. This adds a lot more info, though there's always more.
https://demo1--mozilla-protocol.netlify.app/docs/contributing.html
=> Update and expand contribution docs

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
Bump version to `12.1.1`
- Blocked by #639 
- The CHANGELOG entry  is updated in PR #639
=> Bump version to 12.1.1

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
OMG THEMING HAS FINALLY LANDED 🎉 🥳 💥
=> Bump version to 13.0.0

CHANGELOG.md, package-lock.json, src/assets/sass/protocol/base/elements/_sections.scss, src/assets/sass/protocol/components/_feature-card.scss, src/assets/sass/protocol/components/_hero.scss, src/assets/sass/protocol/includes/_themes.scss
- Adds a spacing them with horizontal and vertical spacing. 
- Using the new spacing decreases outside padding on content containers at 1024px breakpoint (this is in preparation for updating components to use the wider spacing).
- Updates some hard-coded values to use existing variables
---
Fix #345
Fix #536
Not much to see yet. You can compare http://localhost:3000/demos/content-containers.html to prod if you want.
=> Add horizontal and vertical spacing tokens #345 #536

CHANGELOG.md, src/assets/sass/protocol/components/_section-heading.scss, src/assets/sass/protocol/protocol-components.scss, src/pages/demos/section-heading.hbs, src/patterns/atoms/section-heading/heading.hbs, src/patterns/atoms/typographic/headings.hbs
Adds section heading component & docs.
Fix #664
http://localhost:3000/patterns/atoms/section-heading.html
=> Add Section Headings (Fix #664) 

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
Updates to 14.0.0 for all the new goodies.
=> Bump version to 14.0.0

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json, src/assets/sass/protocol/components/_footer.scss
=> Fix footer logo, bump version to 14.0.3

CHANGELOG.md, src/assets/sass/protocol/base/elements/_containers.scss, src/assets/sass/protocol/components/_split.scss, src/patterns/organisms/split/split.hbs
* Use content-box for Split container.
* Trigger column layout at md breakpoint.
* Remove max-width from media in small viewports.
#702 
http://localhost:3000/patterns/organisms/split.html
http://localhost:3000/demos/split.html
http://localhost:3000/demos/split-visual.html
=> Enhancements/fixes for Split component [fix #702]

package-lock.json, package.json
https://github.com/mozilla/protocol-assets/pull/70
=> Update Protocol Assets version to v4.2.0

src/patterns/atoms/section-heading/heading.hbs
=> Fix URL in section-heading/heading.hbs

src/assets/sass/protocol/base/elements/_forms.scss
fixed input element showing repeating background image of the search icon when disabled is set.
#767
Test successfully passed on Protocol.
=> fixed repeating image in input element

CHANGELOG.md, package.json, src/assets/package/README.md, src/assets/package/package.json
Update to v16.0.1 to include two small bug fixes.
=> Bump version to 16.0.1

components/notification-bar/notification-bar--scripted.html, components/notification-bar/notification-bar--scripted.readme.md, components/notification-bar/notification-bar--sticky.html, components/notification-bar/notification-bar--sticky.readme.md, components/notification-bar/notification-bar.config.yml, components/notification-bar/notification-bar.html, components/notification-bar/readme.md
Migrates the notification bar component to Fractal.
http://localhost:3000/components/detail/notification-bar--default
=> Add notification bar

components/picto-card/picto-card.config.yml, components/picto-card/picto-card.html, components/picto-card/readme.md, components/picto/readme.md
Migrates the Picto Card component (which is deprecated, but still in Protocol so still needs to be documented).
http://localhost:3000/components/detail/picto-card--default
http://localhost:3000/components/detail/picto-card--compact
=> Migrate Picto Card

components/sticky-promo/readme.md, components/sticky-promo/sticky-promo.config.yml, components/sticky-promo/sticky-promo.html
http://localhost:3000/components/detail/sticky-promo--default
=> Migrate Sticky Promo

components/footer/01-footer/footer.config.yml, components/footer/01-footer/footer.html, components/footer/01-footer/readme.md, components/footer/02-example-basic/example-basic.html, components/footer/02-example-basic/readme.md
Migrate Footer to Fractal documentation
https://github.com/mozilla/protocol/issues/759
Current: https://protocol.mozilla.org/patterns/organisms/footer.html
http://localhost:3000/components/detail/footer
http://localhost:3000/components/detail/example-basic
=> Migrate footer

.eslintrc.js, theme/assets/js/bidi.js, theme/assets/sass/components/_pen.scss, theme/assets/sass/preview.scss, theme/views/partials/pen/header.nunj, theme/views/partials/scripts.nunj, webpack.docs.build.config.js
Adds a LTR/RTL toggle to the theme to change the text direction of the component preview.
=> Add direction toggle

docs/01-fundamentals/05-design-tokens.md, docs/01-fundamentals/design-tokens.config.yml, theme/assets/sass/components/_tokens.scss, theme/assets/sass/theme.scss
http://localhost:3000/docs/fundamentals/design-tokens
=> Add tokens doc

README.md, docs/01-fundamentals/01-principles.md, docs/01-fundamentals/02-themes.md, docs/01-fundamentals/03-typography.md, docs/01-fundamentals/04-color.md, docs/01-fundamentals/05-design-tokens.md, docs/02-usage/01-overview.md, docs/02-usage/02-framework.md, docs/03-contributing/01-overview.md, docs/03-contributing/02-naming.md, docs/03-contributing/03-css-guide.md, theme/assets/sass/components/_browser.scss, theme/assets/sass/components/_prose.scss
It's a fair bit of content but not much to actually test. It just needs a proofread for spelling/grammar and to make sure everything makes sense and is accurate.
=> Update contributing doc, add usage docs, general doc tidying

CHANGELOG.md, assets/sass/protocol/base/elements/_reset.scss
Add a style rule for the hidden attribute.
#783
=>  Add a style rule for the hidden attribute

components/_preview-dark-unpadded.html, components/_preview-unpadded.html, components/billboard/billboard.config.yml, components/compact-call-out/compact-call-out.config.yml, components/footer/02-example-basic/example-basic.config.yml, components/hero/hero.config.yml, components/layout/01-content-container/content-container.config.yml, components/layout/02-columns/columns.config.yml, components/layout/03-card-layout/card-layout.config.yml, components/layout/04-main-with-sidebar/01-main-with-sidebar/main-with-sidebar.config.yml, components/layout/04-main-with-sidebar/example-sidebar-menu/example-sidebar-menu.config.yml, components/navigation/01-navigation/navigation.config.yml, components/newsletter/newsletter.config.yml, components/split/split.config.yml, theme/assets/sass/components/_navigation.scss, theme/assets/sass/components/_pen.scss, theme/assets/sass/preview.scss
* Add padding to the default preview.
* Add an unpadded preview for full-width components.
* Improve the preview header layout on mobile.
* Make the variant nav "back" button visible on mobile.
=> Theme tweaks, pad preview, add unpadded preview

CHANGELOG.md, assets/package/README.md, assets/package/package.json, package-lock.json, package.json
Bumps release to v16.1.0
N/A
N/A
=> Bump Protocol to v16.1.0

CHANGELOG.md, assets/sass/protocol/components/_button.scss, assets/sass/protocol/includes/forms/_lib.scss
Updated our buttons' focus states to match what was listed the [issue's comment](https://github.com/mozilla/protocol/issues/594#issuecomment-652083403).
#594 
Test out all the button variants: 
http://localhost:3000/components/detail/button--primary
=> Update focus state for buttons

CHANGELOG.md, README.md, assets/package/README.md, assets/package/package.json, package-lock.json, package.json
=> Bump protocol to v17.0.1

package-lock.json, package.json
=> Update Protocol assets to 5.2.0

CHANGELOG.md, assets/package/package.json, package-lock.json, package.json
Bump protocol to version 18.0.0
=> bump protocol version

assets/package/README.md
Forgot to update the package README for the bump to 18.0.0
=> Update project README for 18.0.0

CHANGELOG.md, assets/package/README.md, assets/package/package.json, package-lock.json, package.json
Updates Protocol to version 19.0.0. 
Also updates Protocol assets to 5.3.0.
=> Bump version to 19.0.0

CHANGELOG.md, assets/sass/protocol/components/_button.scss, components/button/button--with-icon.html, components/button/button--with-icon.readme.md, components/button/button.config.yml, components/button/button.html
Allows an inline icon in buttons.
#893 
https://demo2--mozilla-protocol.netlify.app/components/detail/button--with-icon
http://localhost:3000/components/detail/button--with-icon
=> Add optional icon to buttons [fix #893]

CHANGELOG.md, assets/package/README.md, assets/package/package.json, package-lock.json, package.json
=> Bump version to 19.2.0

README.md
This makes sure the instructions for previewing demo branches are actually working.
=> Fix demo preview URLs

.github/ISSUE_TEMPLATE/component_change_request.md, .github/ISSUE_TEMPLATE/new_component_request.md
Distinguishes overview wording between requesting new or changing an existing component.
> ![Screen Shot 2024-07-03 at 18 15 21](https://github.com/mozilla/protocol/assets/1784648/6bfddd5f-5926-44a2-aeab-6637d71ca487)
=> Update issue template wording

.github/dependabot.yml
Updates dependabot to group minor updates into a single PR when possible.
N/A
=> Group dependabot PRs to be a bit less noisy

netlify.toml
Updates historic redirects to still point somewhere relevant.
https://patch-1--mzp-dev.netlify.app/patterns/atoms/typographic-pr0n
https://patch-1--mzp-dev.netlify.app/patterns/molecules/forms-abide$
https://patch-1--mzp-dev.netlify.app/patterns/templates/formst0rm
https://patch-1--mzp-dev.netlify.app/patterns/organisms/hero1n-aff1c10nad0
https://patch-1--mzp-dev.netlify.app/patterns/molecules/notification-barh0pp1ng
https://patch-1--mzp-dev.netlify.app/patterns/molecules/download-buttonl1n3
https://patch-1--mzp-dev.netlify.app/patterns/molecules/emphasis-boxf0rd
https://patch-1--mzp-dev.netlify.app/patterns/molecules/menud3.png
https://patch-1--mzp-dev.netlify.app/patterns/organisms/call-outh0us3
https://patch-1--mzp-dev.netlify.app/patterns/organisms/footerl1ng-haaland
=> Update legacy redirects

CHANGELOG.md, assets/package/README.md, assets/package/package.json, package-lock.json, package.json
=> Publish version 19.3.0

CHANGELOG.md, package-lock.json, package.json
Update protocol-assets to 5.4.0
[Have a look at the Monitor and Relay logos](http://localhost:3000/components/detail/wordmark--products)
=> Update protocol-assets to 5.4.0

package-lock.json, package.json, tests/unit/newsletter.js
Replaces https://github.com/mozilla/protocol/pull/1050
=> Bump sinon from 19.0.2 to 20.0.0

CHANGELOG.md, package-lock.json, package.json
=> Bump protocol-assets

CHANGELOG.md, assets/sass/protocol/components/_footer.scss
- Grey headers
- Horizontal line on mobile
- Larger font for legal
- Terms are a vertical list at smallest screen size
- Tweaks to spacing
---
Fix #1061 
Fix #1063
http://localhost:3000/components/detail/footer
http://localhost:3000/components/detail/example-basic
https://colourcontrast.cc/?background=000000&foreground=bfbfc9
Before and after:
=> Footer style updates (Fix #1063)

CHANGELOG.md, assets/package/README.md, assets/package/package.json, package-lock.json, package.json
Publish 21.1.0. See CHANGELOG for details.
=> Publish 21.1.0

CHANGELOG.md, assets/sass/protocol/base/elements/_forms.scss, assets/sass/protocol/components/_menu-list.scss, assets/sass/protocol/components/_menu.scss, assets/sass/protocol/components/_notification-bar.scss, assets/sass/protocol/components/_sticky-promo.scss, assets/sass/protocol/includes/mixins/_images.scss, components/notification-bar/notification-bar.config.yml, package-lock.json, package.json
Updates Protocol Asset icons and Protocol components using those icons.
Protocol Asset updates
https://github.com/mozilla/protocol-assets/pull/105
https://github.com/mozilla/protocol-assets/pull/110
Expand icon (now Plus)
Arrow Down icon (now Caret Down)
Download icon 
Search icon
Unchanged
- video & audio card icons in card
- social icons in footer
=> Update protocol assets
