package-lock.json, package.json
- Removes unused dev dependencies from the project. We may want to add Babel back in the future, but let's do that as and when we need it, so we're not using an outdated version.
- Also removes `stylelint` dependency, since `gulp-stylelint` installs its own copy.
=> Remove unused dev dependencies (Fixes #29)

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json, src/assets/sass/protocol/protocol.scss
- Use relative paths in pre-compiled CSS (fixes an issue in bedrock).
- Update version number to 0.1.2
=> Use relative paths in pre-compiled CSS

package-lock.json, package.json, src/assets/sass/demos/link-styles.scss, src/assets/sass/docs/site.scss, src/assets/sass/protocol/base/elements/_links.scss, src/data/colors.json, src/pages/demos/link-styles.hbs, src/patterns/atoms/links/text.hbs, src/templates/drizzle/item.hbs
This updates/adds general link styling. I'm still using the old `_colors.scss` file at the moment since Protocol isn't yet consuming the proper tokens. I think some aspects may still be in flux so I've marked it as "inprogress" pending final decisions on color and style.
Meanwhile it can be previewed online and we'll finalize things before merging.
https://demo1--mozilla-protocol.netlify.com/patterns/atoms/links.html
=> Add general link styles

gulp/config.js, gulp/tasks/clean.js, gulp/tasks/default.js, gulp/tasks/serve.js, gulp/tasks/watch.js, package-lock.json, package.json
- Removes deprecated `gulp-util` and replaces with `yargs`
- Removes `@cloudfour/gulp-tasks` and adds our own `clean`, `watch`, and `serve` tasks.
=> Remove dependency on gulp-util and cloudfour/gulp-tasks (Fixes #41)

gulp/config.js, src/templates/default.hbs
I don't think there's much to be gained by a monolith JS file (I can't think why mozilla sites would use it). It's also causing unintended errors, like this:
=> Stop concatenating Protocol JS modules (Fixes #89)

CHANGELOG.md, README.md, docs/README.md, gulp/config.js, src/assets/sass/demos/article.scss, src/assets/sass/demos/billboard.scss, src/assets/sass/demos/card.scss, src/assets/sass/demos/link-styles.scss, src/assets/sass/demos/main-with-sidebar.scss, src/assets/sass/demos/newsletter.scss, src/assets/sass/demos/type-scale.scss, src/assets/sass/docs/protocol-extra.scss, src/assets/sass/protocol/protocol-extra.scss, src/templates/default.hbs
- Creates a `protocol-extra.css` file for publishing compiled component and layout styles.
- Updates README.md with usage instructions.
- Updates CHANGELOG.md with recent commits since last release.
=> Compile component and layout CSS as protocol-extra.css (Fixes #90)

src/pages/demos/card-layout.hbs, src/patterns/molecules/card/collection.yml, src/patterns/molecules/card/extra-small-card.hbs, src/patterns/molecules/card/large-card.hbs, src/patterns/molecules/card/medium-card.hbs, src/patterns/molecules/card/small-card.hbs
Makes card component examples more DRY using handlebars templates.
=> Use handlebars templates for card examples (Fixes #108)

CHANGELOG.md, src/assets/sass/demos/card.scss, src/assets/sass/protocol/components/_card.scss, src/assets/sass/protocol/templates/_card-layout.scss, src/pages/demos/card-picto-layout.hbs, src/patterns/molecules/card/extra-small-card.hbs, src/patterns/molecules/card/large-card.hbs, src/patterns/molecules/card/medium-card.hbs, src/patterns/molecules/card/picto-card-compact.hbs, src/patterns/molecules/card/picto-card.hbs, src/patterns/molecules/card/small-card.hbs, src/patterns/templates/card-layout/card-layout.hbs
Fixes #154, #155.
- Adds a new Picto Card component with compact variation (happy to choose a different name, but I thought this sounded better than something like "Icon Card").
- Updates card layout classes to support groups of 2 & 3 Picto Cards.
Demo:
- https://mozilla-protocol.netlify.com/patterns/molecules/card.html#picto-card
- https://mozilla-protocol.netlify.com/patterns/molecules/card.html#picto-card-compact
- https://mozilla-protocol.netlify.com/patterns/molecules/card.html
=> Add Picto Card component (Fixes #154, #155)

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json, src/assets/sass/protocol/components/_hero.scss
This fixes the bug and also updates Protocol to 2.1.1.
Explanation for posterity: When the CSS is post-processed some scripts will attempt to resolve all instances of `url()` and will throw an error when a referenced file isn't found, potentially breaking a build. While this shouldn't have any effect when `url()` appears in a feature query (the asset isn't actually loaded, the query only tests for support of the property) it causes problems with other kinds of post-processing. Since file paths are somewhat dynamic it can be hard to ensure an asset exists in the right location, so in general we should probably just avoid `url()` references in feature queries and test for a related feature instead.
=> Avoid referencing URLs in feature queries

CHANGELOG.md, src/assets/js/docs/bidi.js, src/assets/sass/docs/site.scss, src/templates/drizzle/bidi.hbs, src/templates/drizzle/item.hbs
Fixes #150
Figured it would take less time to implement this than it would to keep manually changing attributes whilst in dev. Already noticed a few minor RTL bugs on various components whilst testing this :)
Super high-tech gif preview:
=> Add bidi control to component previews (Fixes #150)

package-lock.json, package.json, src/assets/sass/demos/card.scss, src/assets/sass/demos/type-scale.scss, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/components/_call-out.scss, src/assets/sass/protocol/components/_card.scss, src/assets/sass/protocol/components/_modal.scss, src/assets/sass/protocol/components/_sidebar-menu.scss, src/assets/sass/protocol/includes/_variables.scss
Notable updates:
- The close icon for the modal has changed (to be consistent with the close icon for the navigation). It should still display correctly.
- The token value for `$color-gray-90` has been corrected, so existing occurences should be updated to `$color-gray-60`.
- We now have a `$mq-high-res` token, so we can remove it from `_variables.scss`.
=> Update protocol/assets v1.0.1, protocol/tokens v2.0.0

CHANGELOG.md, package.json
It occured to me that there was a hole in our publishing steps for NPM, which did not cover someone's local NPM dependencies being out of date. This could result in unintentional publishing of a version of protocol-assets to protocol-tokens which does not match up to the version number in `package.json` for the `master` branch. This could happen quite easily when switching between feature branches, for example.
This PR updates the NPM `pretest` script to always do an `npm install` before `npm test` is run, so the `./dist` folder should always include the expected assets.
=> Ensure documented publishing steps include updating dependencies

CHANGELOG.md, src/assets/js/protocol/protocol-menu.js
This is a small bug fix to workaround a quirk in bedrock's `classList` polyfill for IE9. I filed a separate issue for bedrock to investigate updating our polyfill to the latest version on MDN:
https://github.com/mozilla/bedrock/issues/6221
=> Workaround for IE9 navigation bug in bedrock's classList polyfill (#182)

CHANGELOG.md, src/assets/js/protocol/protocol-lang-switcher.js, src/patterns/molecules/language-switcher/language-switcher.hbs, tests/unit/protocol-lang-switcher.js
=> Rename '.mzp-c-language-switcher-select' class (Fixes #242)

Jenkinsfile
They were using the sparkels emoji because it was expecting a status of "failure" instead of "failed" and sparkels is the default.
=> Fix slack failure notifications

src/templates/drizzle/nav.hbs
Feel free to reject this. I've been looking at Protocol a bunch today and keep expecting a GH link to be in the sidebar.
=> add link to github repo in sidebar

CHANGELOG.md, src/assets/sass/protocol/components/_menu-item.scss, src/assets/sass/protocol/components/_menu.scss, src/pages/demos/navigation.hbs, src/patterns/molecules/menu/menu-item.hbs
* Navigation items that are links without menus get hover styles (#304)
* Let menu item titles not be links (#307)
* Updates Navigation demo with menu that is example the above 2 cases
* moved links onto the menu-item templates as attributes
=> Menu styles tweaks

CHANGELOG.md, src/assets/sass/protocol/components/_footer.scss
Don't repeat social icons (Fix #317)
Fix #317
Only effected the instagram icon, I don't think there is one on any of the demo pages but you can swap the class on the link for testing purposes.
=> Don't repeat social icons (Fix #317)

CHANGELOG.md, src/assets/js/protocol/protocol-menu.js, src/assets/js/protocol/protocol-navigation.js, src/assets/sass/protocol/components/_menu.scss, src/assets/sass/protocol/components/_navigation.scss, src/patterns/molecules/menu/menu.hbs, tests/unit/protocol-menu.js, tests/unit/protocol-navigation.js
This PR makes the menu molecule more resilient to JS errors, by no longer relying on the `js` and `np-js` global class names.
#320
=> Make the Menu molecule more resilient to JS errors (Fixes #320)

CHANGELOG.md, src/assets/js/protocol/protocol-navigation.js, src/pages/demos/navigation.hbs, src/patterns/organisms/navigation/navigation.hbs
- make navigation button code only open its associated menu
- update navigation template macro
- add download button and mozilla logo as optional parameters
- remove id from template as it was not being consumed
- add second menu to navigation demo page
=> Enable second navigation menu on pages (#300)

CHANGELOG.md, src/patterns/molecules/menu/menu.hbs
Adds an example of a menu to the menu page in the docs.
Fix #322 
The menu drop down overflows the sample container. I experimented with containing it inside the container but then it ends up really squished. It's buggy but it accurately represents the menu behaviour too. 🤷‍♀️
=> Add example menu to menu molecule page (Fix: #322)

CHANGELOG.md, src/assets/sass/protocol/components/_navigation.scss, src/pages/demos/navigation.hbs, src/patterns/organisms/navigation/navigation.hbs
Add optional label to navigation mobile menu button.
Fix #313
- RTL
- small and large screens
- label displays when it should, does not when it shouldn't
- no demo for this right now, it makes sense to add it after #309 merges
=> Add optional label to navigation mobile menu button. #313

CHANGELOG.md, src/assets/sass/protocol/base/elements/_links.scss, src/assets/sass/protocol/components/_button.scss, src/assets/sass/protocol/includes/_mixins.scss
Use light-links mixin in `.t-dark` theme links.
Add visited links styles to light-links mixin.
Fix #335 
This underlined all child buttons under `.t-dark` themed elements... hence the important. Let me know if you think this is a bad idea I'm a bad person and I should feel bad.
=> Use light-links mixin in t-dark theme #335

CHANGELOG.md, src/assets/sass/protocol/base/elements/_details.scss, src/assets/sass/protocol/includes/mixins/_details.scss
- Move details and summary styles into mixins classes
- Add right padding to summary to avoid over-lapping with toggle image
---
Fix #332 Fix #331
=> Details extend and fix text overlapping button bug

CHANGELOG.md, src/assets/sass/protocol/base/elements/_quotes.scss
Over-ride zilla with open sans when a blockquote is on a firefox themed page.
Fix #303
Hopefully pretty straight forward.
=> Add blockquote mzp-t-firefox theme #303

CHANGELOG.md, package-lock.json, package.json, src/assets/sass/demos/call-out.scss, src/assets/sass/demos/card.scss, src/assets/sass/demos/hero.scss, src/assets/sass/demos/type-scale.scss, src/assets/sass/docs/site.scss, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/components/_billboard.scss, src/assets/sass/protocol/components/_button.scss, src/assets/sass/protocol/components/_call-out.scss, src/assets/sass/protocol/components/_card.scss, src/assets/sass/protocol/components/_feature-card.scss, src/assets/sass/protocol/components/_footer.scss, src/assets/sass/protocol/components/_hero.scss, src/assets/sass/protocol/components/_language-switcher.scss, src/assets/sass/protocol/components/_modal.scss, src/assets/sass/protocol/components/_newsletter-form.scss, src/assets/sass/protocol/components/_picto-card.scss, src/assets/sass/protocol/components/_sidebar-menu.scss, src/assets/sass/protocol/templates/_card-layout.scss
Pulls in new tokens. Updates colours and units.
- replaces `margin-` and `padding-` units with `spacing-`
- darkens some greys for new colour palette
---
Fix #339
Changes can be previewed on [demo1](https://demo1--mozilla-protocol.netlify.com/demos/). I would appreciate a visual review from someone on the design team.
The darkness of the greys has shifted please have a look at the dark theme templates.
=> Update Tokens to 3.0.0

CHANGELOG.md, src/assets/sass/protocol/components/_call-out.scss, src/assets/sass/protocol/components/_feature-card.scss
Uses the `flexbox` mixin to add vendor prefixes in places where we want `display: flex`
-  ~I have documented this change in the design system.~
Fix #218 and a few other places where the code was the same and so might have had duplicate bugs.
I left the one `display: flex` inside the `@supports` declaration because I think we would have to re-write the `@supports` declaration for each prefix. 
Check the Call Out and Feature Card components.
=> Add vendor prefixes to flex box uses (#218)

CHANGELOG.md, src/assets/sass/protocol/includes/mixins/_at2x.scss
When the `at2x` gets `contain` as the second parameter it no longer sets the height to auto, instead it does not add a height value.
Fix #336.
This was annoying to figure out so please don't assume it's fine by looking at it, do give the code a test.
=> at2x accepts contain as a single parameter (#336)

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json, src/assets/sass/protocol/includes/mixins/_at2x.scss
Fixes a bug in at2x mixin and publishes version 6.0.1.
Fix #368
I found it useful to  copy the mixin into code pen and try the 4 following combinations to make sure the right thing is being output:
- no size attributes, should output auto
- just a width (height should be auto)
- width and height
- just contain (should be no height: auto).
=> Fix at2x error and publish

CHANGELOG.md, src/assets/sass/protocol/components/_button.scss
Updates the product button theme colors for the upcoming trailhead campaign pages.
#380
Both primary and secondary download button themes should reflect the new color.
=> Update product button theme color (Fixes #380)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_quotes.scss, src/patterns/atoms/typographic/quotes.hbs
- Add citation styles to blockquotes. 
- Decreases font size of blockquotes.
#366
=> Add citation style to blockquote and decrease font size. (#366)

.github/ISSUE_TEMPLATE/bug_report.md
The bug tag is applied automatically, we don't need this info twice.
=> Remove "[bug]" from issue template title.

CHANGELOG.md, src/assets/js/protocol/protocol-newsletter.js
-  ~I have documented this change in the design system.~
Fix #400 
Include newsletter.js in a component that doesn't need it on the master branch, verify you get the error, switch to this branch and verify you do not.
`<script src="{{@root.baseurl}}/assets/protocol/protocol/js/protocol-newsletter.js"></script>`
=> Newletter.js only runs when there is a newsletter (#400)

README.md, src/pages/docs/contributing.md, src/pages/docs/css-guide.md, src/pages/docs/naming.md, src/pages/index.hbs
Adds a basic contributor guide, mostly with plain-English steps for getting the site installed.
This also adds a note to the front page and readme that clarified Protocol is under development and likely to change, lest someone come along and think it's "complete" when it clearly is missing a bunch of stuff and things are going to be changing soon.
=> Add contribution guide

CHANGELOG.md, src/assets/sass/protocol/includes/mixins/_details.scss
Details button gets cursor:pointer when hovered
Fix #367
Hover over the some buttons on the details page, see if the cursor updates.
=> Details button gets cursor:pointer when hovered (#367)

CHANGELOG.md, src/assets/sass/protocol/components/_article.scss
Article max-width restricted to size of parent container 
Fix #422
The original problem shows up when a `<pre>` tag is inside the article content.
=> Article max-width restricted to size of parent container (#422)

CHANGELOG.md, package-lock.json, src/assets/js/protocol/protocol-notification-bar.js, src/assets/sass/protocol/components/_notification-bar.scss, src/assets/sass/protocol/protocol-extra.scss, src/patterns/molecules/notification-bar/notification-bar.hbs, tests/karma.conf.js, tests/unit/protocol-notification-bar.js
Adds the notification bar component used on /thanks and /whatsnew
#383
https://github.com/mozilla/bedrock/issues/7468
https://demo2--mozilla-protocol.netlify.com/patterns/molecules/notification-bar.html
- Supports different styles:
- Success
- Warning
- Error
- Click
- Dismiss is optional.
=> Add notification bar component. (Fixes #383)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_links.scss, src/assets/sass/protocol/components/_button.scss, src/pages/fundamentals/themes.hbs
Change font to Metropolis when cta-links and buttons are under `.mzp-t-firefox`
Fix #468
- Firefox themed cta-links can be found on: http://localhost:3000/demos/feature-card.html
- For the buttons I just added the theme class using dev tools.
=> Firefox theme CTAs should use the Metropolis Font (#468)

CHANGELOG.md, src/assets/sass/protocol/components/_newsletter-form.scss
We should be able to embed the newsletter form in places where we don't want an image next to it. So, I have separated the form formatting from the layout when used with an image.
- edited form styles to work when not nested under .mzp-c-newsletter
- moved all two column/grid styles to only apply when nested under .mzp-c-newsletter
Fix #444
- Display should be identical before and after changes.
- Form should still format properly when not nested under .mzp-c-newsletter (ie, elements should have proper spacing, errors and details should be hidden)
=> Separate newsletter form and newsletter layout styling (#444)

.github/ISSUE_TEMPLATE/component_change_request.md, .github/ISSUE_TEMPLATE/new_component_request.md, CHANGELOG.md, src/pages/docs/contributing.md
This adds issue templates for creating new components and updating existing components
This resolves #379
No testing necessary, this is a documentation change
=> add component issue templates

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json
Bumps version to 8.1.0 for publishing to NPM
N/A
I'm following the steps here: https://github.com/mozilla/protocol/tree/master/docs#publishing-to-npm
=> Bump version to 8.1.0

CHANGELOG.md, package-lock.json, package.json, src/assets/sass/protocol/components/_call-out.scss, src/assets/sass/protocol/components/_card.scss, src/assets/sass/protocol/components/_hero.scss, src/assets/sass/protocol/components/_menu.scss, src/assets/sass/protocol/components/_modal.scss, src/assets/sass/protocol/components/_navigation.scss, src/assets/sass/protocol/components/_notification-bar.scss, src/assets/sass/protocol/includes/mixins/_details.scss, src/assets/sass/protocol/includes/mixins/_images.scss, src/pages/demos/navigation.hbs, src/patterns/organisms/call-out/call-out.hbs, src/patterns/organisms/hero/hero-branded.hbs
- Point all ui icons to the new locations
- Add background-size declarations to places icons are used (new icon files are larger)
- Remove `-black` from places referenceing black icon files
- Update logo urls
- Remove focus theme
---
Fix #479
- All icons that were inside the ui folder have been moved
- Background-size declarations have been added to places icons are used (new icon files are larger)
- Black icons no longer have -black in the file name.
- mzp-t-product themes still work as expected
=> Update @mozilla-protocol/assets to 3.0.0 (#479)

CHANGELOG.md, src/assets/js/protocol/protocol-modal.js, src/assets/js/protocol/protocol-notification-bar.js
Hi @alexgibson this is a continuation of #488 – in updating my fork accidentally closed that PR and now GH won’t let me add new commits to it. Sorry about that, and thanks for taking a look.
As requested:
=> Use window.Mzp in Modal and Notification components

CHANGELOG.md, src/assets/sass/protocol/base/elements/_links.scss, src/assets/sass/protocol/components/_menu-list.scss
CTA links now use text underlines instead of borders
Fix #490
- cta-links http://localhost:3000/patterns/atoms/links.html
- cta theme for menu list http://localhost:3000/patterns/molecules/menu-list.html
- cta links in dark themes: http://localhost:3000/demos/feature-card.html
=> CTA links now use text underlines instead of borders (#490)

CHANGELOG.md, src/assets/sass/protocol/components/_menu-list.scss
Fix #503 
http://localhost:3000/patterns/molecules/menu-list.html
=> Menu List Firefox theme CTA uses firefox-font (#503)

CHANGELOG.md, src/assets/js/protocol/protocol-notification-bar.js, src/patterns/molecules/notification-bar/notification-bar.hbs, tests/unit/protocol-notification-bar.js
This changeset adds support for an optional hyperlink ("call to action"/CTA) to be added after the main text in a JS-triggered `NotificationBar` component. 
Prior to this changeset, it was not possible to use JS to create a notification with a working CTA link.
An optional options object lets the developer specify the text for inside the link, the URL for its href and, optionally, another object of additional attributes which are all then applied to the link.
Includes tests.
Resolves https://github.com/mozilla/protocol/issues/460
* Check out the build
* `npm start` to get it running locally
* Go to http://localhost:3000/patterns/molecules/notification-bar.html
* Click the "Open Notification" button to see the default/example notification now includes a CTA.
=> Support an optional CTA link in a JS-created NotificationBar (#460)

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json, src/assets/sass/demos/card.scss, src/assets/sass/demos/hero.scss, src/assets/sass/demos/link-styles.scss, src/assets/sass/demos/type-scale.scss, src/assets/sass/docs/prism.scss, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/base/elements/_quotes.scss, src/assets/sass/protocol/base/elements/_sections.scss, src/assets/sass/protocol/base/elements/_typography.scss, src/assets/sass/protocol/components/_billboard.scss, src/assets/sass/protocol/components/_button.scss, src/assets/sass/protocol/components/_call-out.scss, src/assets/sass/protocol/components/_card.scss, src/assets/sass/protocol/components/_emphasis-box.scss, src/assets/sass/protocol/components/_feature-card.scss, src/assets/sass/protocol/components/_footer.scss, src/assets/sass/protocol/components/_hero.scss, src/assets/sass/protocol/components/_language-switcher.scss, src/assets/sass/protocol/components/_menu-item.scss, src/assets/sass/protocol/components/_menu-list.scss, src/assets/sass/protocol/components/_menu.scss, src/assets/sass/protocol/components/_navigation.scss, src/assets/sass/protocol/components/_notification-bar.scss, src/assets/sass/protocol/components/_picto-card.scss, src/assets/sass/protocol/components/_sidebar-menu.scss
Updates assets to 3.0.1 and tokens to 5.0.1 (we never updated to tokens 4 so it's been a long time coming). This adds new tokens for border radius, box shadows, restores the Mozilla brand colors, updates the Firefox brand colors, and updates font stacks for the different brands.
Some token names have changed making this a breaking change downstream so this also includes a version bump to 11.0.0
#449
=> Update tokens and assets

CHANGELOG.md, src/assets/sass/protocol/components/_notification-bar.scss, src/patterns/molecules/notification-bar/notification-bar.hbs
=> Add link color styles to notification bar (Fixes #541)

CHANGELOG.md, src/assets/sass/demos/hero.scss, src/assets/sass/demos/type-scale.scss, src/assets/sass/docs/site.scss, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/base/elements/_quotes.scss, src/assets/sass/protocol/base/elements/_typography.scss, src/assets/sass/protocol/base/utilities/_typography.scss, src/assets/sass/protocol/components/_article.scss, src/assets/sass/protocol/components/_billboard.scss, src/assets/sass/protocol/components/_call-out.scss, src/assets/sass/protocol/components/_card.scss, src/assets/sass/protocol/components/_feature-card.scss, src/assets/sass/protocol/components/_hero.scss, src/assets/sass/protocol/components/_menu-item.scss, src/assets/sass/protocol/components/_modal.scss, src/assets/sass/protocol/components/_newsletter-form.scss, src/assets/sass/protocol/components/_picto-card.scss, src/assets/sass/protocol/includes/mixins/_typography.scss, src/assets/sass/protocol/protocol.scss, src/pages/fundamentals/typography.hbs, src/patterns/atoms/typographic/headings.hbs
Add atomic heading utility classes.
- also change all instances of text-display to text-title
See #297
=> Add title size utility class (#297)

CHANGELOG.md, src/assets/js/protocol/protocol-navigation.js, src/assets/js/protocol/protocol-supports.js, src/assets/sass/protocol/components/_navigation.scss, src/pages/demos/navigation.hbs, src/patterns/organisms/navigation/navigation.hbs, tests/unit/protocol-navigation.js
Implement sticky scrolling behaviour for navigation component as an opt-in feature
#560
Demo: https://demo2--mozilla-protocol.netlify.com/demos/navigation.html
=> Implement sticky navigation (Fixes #560)

CHANGELOG.md, src/assets/sass/protocol/components/_notification-bar.scss
When updating the notification bar in https://github.com/mozilla/protocol/pull/553/ I left out a rule to center it in the viewport when it's non-sticky. D'oh!
=> center the notification bar in larger viewports

CHANGELOG.md, src/assets/sass/protocol/components/_button.scss
Makes `button` and `a` elements of class `mzp-c-button` the same height
N/a
http://localhost:3000/patterns/atoms/buttons.html
=> Button line-height bug fix

CHANGELOG.md, src/assets/sass/protocol/base/elements/_forms.scss, src/patterns/atoms/forms/errors.hbs
Small tweaks to form error styles:
- use new form variables
- add unique IDs to error demo
---
Part of #508
http://localhost:3000/patterns/atoms/forms.html#errors
http://localhost:3000/demos/newsletter.html
=> Tweak form error styles (#508)

CHANGELOG.md, src/assets/sass/protocol/includes/_mixins.scss, src/patterns/molecules/notification-bar/notification-bar.hbs
Switch to negative text indent for image replacement
Fix #519
See also https://github.com/mozilla/bedrock/issues/8084
Components with image replacements:
- footer
- menu
- modal
- navigation
- notification bar
=> Switch to negative text indent for image replacement (#519)

CHANGELOG.md, src/assets/sass/protocol/components/_button.scss, src/assets/sass/protocol/components/forms/_button-container.scss, src/assets/sass/protocol/protocol-extra.scss, src/pages/demos/forms/button-alignment.hbs, src/patterns/molecules/forms/collection.yml, src/patterns/molecules/forms/container.hbs, src/patterns/molecules/forms/set.hbs
Adds a button container element for forms, with a few alignment options. Also adds styling for the small button info text.
This is built on @stephaniehobson's work, which was in turn built on the work @kkellydesign did on SUMO.
#580 
https://demo1--mozilla-protocol.netlify.app/patterns/molecules/forms.html#button-container
https://demo1--mozilla-protocol.netlify.app/demos/forms/button-alignment.html
=> Add button container and alignment options (#580)

src/pages/fundamentals/icons.hbs
The new icons page is super-handy but when folks on the brand and UX teams saw it, it sparked a bigger conversation about updating our icon set and writing some usage guidelines. The consensus was that we shouldn't encourage people to use the icons right now because they're going to change soon.
So this change doesn't delete the page but removes it from the side nav until we have a chance to refine the icons and improve documentation (you can still reach it directly if you know the URL) and adds a stronger warning.
=> Icons page: update intro, de-list from nav

CHANGELOG.md, src/assets/sass/protocol/base/elements/_sections.scss
The border-box declaration was removed in #595 but it probably shouldn't have been. This puts it back.
#611 
Test responsiveness in small viewports. There should be no crawlbars as far down as 320px (smaller than that still crawls but that's OK).
http://localhost:3000/demos/content-containers.html
http://localhost:3000/demos/content-container-vis.html
=> [fix #611] Reduce content container min-width

CHANGELOG.md, src/assets/sass/protocol/components/_navigation.scss
Navigation is max-content width on large screens (#615)
Fix #615
http://localhost:3000/demos/navigation.html on a screen over 1440px wide.
=> Navigation is max-content width on large screens (#615)

CHANGELOG.md, src/assets/sass/protocol/components/_card.scss, src/assets/sass/protocol/templates/_card-layout.scss
Remove max-width from cards in card-layout.
Fix #620
- This is a very brittle way of doing this, it depends on the card template CSS to be included after the card CSS. Should I increase the specificity to avoid this problem?
- I am wondering if we should divorce the card widths from the card sizes all together. Perhaps that is a bigger issue that should be considered separately. Do we ever use the cards without the layout options?
=> Remove max-width from cards in card-layout (Fix #620)

CHANGELOG.md, src/assets/js/protocol/protocol-sticky-promo.js, src/assets/sass/protocol/components/_sticky-promo.scss, src/patterns/molecules/sticky-promo/sticky-promo.hbs
The sticky promo now requires an appended class to show. 
I also added a helper class to show the sticky promo on page load, providing backwards compatibility for previous behavior.
https://github.com/mozilla/bedrock/issues/9406
Enter helpful notes for whoever code reviews this change.
=> Fix #638 - Revise the sticky promo to be hidden by default 

CHANGELOG.md, src/assets/js/protocol/protocol-sidemenu.js
Check for sidemenu before initializing 
Fix #643
You can replicate the error on http://localhost:3000/demos/article.html by removing the menu html from `sidebar-menu.hbs`
=> Check for sidemenu before initializing (#643)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_forms.scss, src/assets/sass/protocol/components/_footer.scss, src/assets/sass/protocol/includes/_mixins.scss, src/pages/docs/contributing.md
Adds a new mixin for explicitly white links (as opposed to the inverted theme colors).
#648
=> Add white-links mixin [fix #648]

CHANGELOG.md, src/assets/sass/docs/site.scss, src/assets/sass/protocol/components/_button.scss
Fixes button focus color by explicitly declaring it for `a.mzp-c-button:focus`, overriding the color from the common `:link:focus` pseudo-class. Also fixes a docs issue with some button examples lacking a dark background.
Button focus color: #655 
Button example backgrounds: #656 
For the focus color you'll need to test an instance of a link styled as a button, such as in the first example on the hero demo page: http://localhost:3000/demos/hero.html
Button examples backgrounds:
http://localhost:3000/patterns/atoms/buttons.html#product-secondary-dark
http://localhost:3000/patterns/atoms/buttons.html#neutral-dark
=> Fix button focus color [fix #655]

CHANGELOG.md, src/assets/sass/demos/card.scss, src/assets/sass/demos/content-container.scss, src/assets/sass/demos/hero.scss, src/assets/sass/demos/link-styles.scss, src/assets/sass/protocol/base/utilities/_backgrounds.scss, src/assets/sass/protocol/components/_call-out.scss, src/assets/sass/protocol/protocol.scss, src/pages/demos/hero.hbs, src/pages/fundamentals/themes.md
This adds a common theme class for applying an alternative background color: `.mzp-t-background-alt`
Also standardizes `.mzp-t-dark` class to use the theme variable for inverse backgrounds.
I haven't really documented it because I'm not sure where that documentation should go... we probably need to think about that. I'd suggest a new doc page for these kinds of utility and theme classes. There's [an older issue about properly documenting the "dark" theme](#628 ), that would go in the same place. I can work on better docs but I don't want to hold up getting this class added.
http://localhost:3000/demos/hero.html uses the alt background class on a few examples
=> Add theme class for alt background color [no bug]

CHANGELOG.md, src/assets/sass/demos/columns.scss, src/assets/sass/demos/picto.scss, src/assets/sass/protocol/components/_picto.scss, src/assets/sass/protocol/protocol-components.scss, src/assets/sass/protocol/templates/_multi-column.scss, src/pages/demos/columns.hbs, src/pages/demos/picto.hbs, src/patterns/molecules/picto-card/picto-card-compact.hbs, src/patterns/molecules/picto-card/picto-card.hbs, src/patterns/molecules/picto/picto-center.hbs, src/patterns/molecules/picto/picto-side.hbs, src/patterns/molecules/picto/picto.hbs, src/patterns/templates/columns/columns.hbs, src/patterns/templates/content-container/content-container.hbs, src/static/img/picto/image.svg
This adds a new component called simply "picto" to replace the original picto card. It's a small block of content featuring an image (typically a small icon, hence the name "picto"), a headline, and a short blurb.
Also adds a mutli-column layout template. It's content-agnostic and doesn't impose any other layout or styling, it's literally just a container to create a simple set of even columns (two, three, or four). The multi-column container should be used in combination with a content container.
#233 - multi-column layout
#382 - new picto
https://demo1--mozilla-protocol.netlify.app/patterns/molecules/picto.html
https://demo1--mozilla-protocol.netlify.app/demos/picto.html
https://demo1--mozilla-protocol.netlify.app/patterns/templates/columns.html …
=> New picto component [fix #382] and multi-column layout [fix #233]

CHANGELOG.md, src/assets/sass/docs/site.scss, src/assets/sass/protocol/base/elements/_titles.scss, src/assets/sass/protocol/components/_article.scss, src/pages/demos/theme-firefox.hbs, src/pages/demos/theme-mozilla.hbs
Generic heading elements are downsized, starting at `lg` for `h1` and stepping down to `3xs` for `h6`. I did a trial run on bedrock and found no ill effects. Most components have sizes declared explicitly already and any custom pages that need smaller headings are also declaring them explicitly to override the defaults.
http://localhost:3000/patterns/atoms/typographic.html#heading-elements
=> Reduce base heading sizes [no bug]

src/assets/sass/protocol/includes/_lib.scss
Compiling Protocol with the [sass](https://www.npmjs.com/package/sass) package gives the below error.
```
(body-font-family: (Inter, X-LocaleSpecific, sans-serif), button-font-family: (Metropolis, Inter, X-LocaleSpecific, sans-serif), title-font-family: (Metropolis, Inter, X-LocaleSpecific, sans-serif)) isn't a valid CSS value.
```
The line that caused this bug is:
https://github.com/mozilla/protocol/blob/b8542c88bdeede8dfc5b6c2614bcc6f811f4a505/src/assets/sass/protocol/includes/_themes.scss#L223
After investigating, I found that the reason why sass was not able to understand this line was because at the time of compiling, the function `map-collect` was not available. I then looked at the order of import and found that `themes` was imported before `functions`. …
=> Change the import order to fix sass compiling bug

CHANGELOG.md, package-lock.json, package.json, src/assets/package/README.md, src/assets/package/package.json, src/templates/drizzle/nav.hbs
This includes a bug fix in the main _lib.scss and also fixes the logo in the doc site nav (which I missed because I still had old assets on my local 🤦). I'll be more careful when publishing this.
=> Bump version to 14.0.1

CHANGELOG.md, src/assets/js/protocol/protocol-details.js, src/assets/js/protocol/protocol-lang-switcher.js, src/assets/js/protocol/protocol-menu.js, src/assets/js/protocol/protocol-modal.js, src/assets/js/protocol/protocol-navigation.js, src/assets/js/protocol/protocol-notification-bar.js, src/assets/js/protocol/protocol-sticky-promo.js, src/assets/js/protocol/protocol-supports.js, src/assets/js/protocol/protocol-utils.js
Ensures JS components are always accessible via `window.Mzp` namespace.
~- [ ] I have documented this change in the design system.~
#687
=> Set global Mzp namespace to default to window as root (Fixes #687)

.github/workflows/node.js.yml, .travis.yml, CHANGELOG.md
This is more urgent now that [travis ci is shutting down for real](https://blog.travis-ci.com/2021-05-07-orgshutdown)
This fixes #652 
N/A, check ci status
=> Migrate continuous integration to GitHub actions (fixes #652)

CHANGELOG.md, src/assets/sass/protocol/base/elements/_details.scss, src/patterns/molecules/details/details-custom.hbs
The native details element was getting double icons in IE11. It was doubling up because the native element is being styled, but it also gets classes and a button from the polyfill. This overrides native styling when the polyfill applies.
#658 
http://localhost:3000/patterns/molecules/details.html
It's really just an issue in IE11 since I think that's the only browser that gets the polyfill. Older IEs get no fancy details support and modern browsers get native support.
=> Override styling native summary element when it’s polyfilled [fix #658]

CHANGELOG.md, src/assets/sass/protocol/components/_picto.scss
Picto has a rule zeroing the bottom margin in multi-column layouts. However, the columns only kick in at larger viewports so multi-column pictos had no vertical spacing when they stacked on mobile. This wraps that zero margin rule in a media query so it only takes effect with the columns do.
#699 
http://localhost:3000/patterns/molecules/picto.html
http://localhost:3000/demos/picto.html
=> Picto bottom margins in multi-column [fix #699]

src/patterns/organisms/call-out/call-out.hbs, src/patterns/organisms/hero/hero.hbs, src/patterns/organisms/split/split.hbs
Added **No-nos** section in Split, Hero, and Call Out document pages, and mentioned they shouldn't be placed in `mzp-l-content` containers
#706 
localhost:3000/patterns/organisms/split.html
localhost:3000/patterns/organisms/hero.html
localhost:3000/patterns/organisms/call-out.html
=> Container update docs

CHANGELOG.md, src/assets/sass/protocol/components/_hero.scss, src/assets/sass/protocol/components/_picto-card.scss, src/patterns/organisms/hero/hero-branded.hbs, src/patterns/organisms/hero/hero-image.hbs, src/patterns/organisms/hero/hero.hbs
#709
Running `npm install` should display warnings in console for each deprecated component
=> Add warning when compiling deprecated components (Fixes #709)

CHANGELOG.md, src/pages/fundamentals/themes.md
Adds small note to https://protocol.mozilla.org/fundamentals/themes.html documentation to explain how SCSS variables should work across multiple files.
https://github.com/mozilla/protocol/issues/697
Check note is on correct page. Confirm clarity of note content.
=> Update docs to clarify brand variable use (fixes #697)

CHANGELOG.md, src/assets/sass/protocol/base/utilities/_titles.scss, src/assets/sass/protocol/components/_split.scss, src/assets/sass/protocol/components/logos/_logo.scss, src/assets/sass/protocol/components/logos/_wordmark.scss, src/pages/demos/split-visual.hbs, src/pages/demos/split.hbs, src/patterns/atoms/logo/logo.hbs, src/patterns/atoms/logo/wordmark.hbs, src/patterns/molecules/feature-card/feature-card.hbs, src/patterns/organisms/split/split-bg.hbs, src/patterns/organisms/split/split.hbs
* Added content width classes to Split component. This will help it play nicer when combined with other widths on the same page.
* Add bottom margins to logos and wordmarks [see #712]
* Added an `mzp-u-title-3xs` utility class. We revised the type scale after these classes were created and added another heading size, but didn't add a class for the new one.
* Misc doc updates. Rewrote Split docs for better clarity and easier reference.
#712 - add default bottom margins on logos
http://localhost:3000/patterns/organisms/split.html
http://localhost:3000/demos/split.html
http://localhost:3000/patterns/atoms/logo.html
=> Split updates, logo margins, 3xs title class

CHANGELOG.md, src/assets/sass/protocol/components/_card.scss, src/pages/demos/card-layout.hbs, src/patterns/molecules/card/dark-mode-card.hbs
Added some rules when adding the `.mzp-t-dark` class to enable dark mode styled cards. I used the same themes as in other areas of protocol, but let me know if anything should change. 
Added some rules to override the links and `p` tags in the card component so the color would be visible for dark mode. Since dark mode isn't listed outside of the themes section, I wasn't sure how it should be documented. 
#714
Wasn't sure how we would want to add this card _variant_ to the documentation since dark mode is only referenced in the themes section of the docs. If you build this locally, you can just add the `.mzp-t-dark` class to any card to it's container. I created the rules so it would have to be on whichever element has the `mzp-c-card` class.
=> had rules to card with mzp-t-dark class

bin/build.sh
Recent deployments have been failing because our versions of some dependencies no longer work in Node 10, which is what the build script is using. This updates the build to Node 14 which should support the other dependencies.
Recent failure: https://gitlab.com/mozmeao/protocol/-/jobs/1589827585
`Error: yargs supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs#supported-nodejs-versions`
=> Update Node version in build.sh

.gitlab-ci.yml
Stage deployments were still watching for changes in a branch that no longer exists. This should fix it.
=> Rename master to main in gitlab-ci.yml

CHANGELOG.md, src/assets/sass/protocol/components/logos/_logo.scss, src/assets/sass/protocol/components/logos/_wordmark-product-vpn.scss, src/assets/sass/protocol/components/logos/_wordmark.scss
We are working towards a smaller protocol-assets dependency size. This will involve removing PNG assets, which will break our current logo and wordmark mixins. We want to preserve the use of these mixins, but return SVG assets instead of PNG.
~⚠️ Cannot merge until Focus logo is available in SVG with next protocol-assets version~ Merged! All clear
https://github.com/mozilla/protocol/issues/723
http://localhost:3000/demos/logo.html
Check all logos look as expected
=> Use SVG instead of PNG for logos and wordmarks [#723]

CHANGELOG.md, src/assets/js/protocol/protocol-navigation.js, src/patterns/organisms/navigation/navigation.hbs, tests/unit/protocol-navigation.js
We want to remove sticky behaviour from the nav for users who prefer reduced motion.
https://github.com/mozilla/protocol/issues/733
You'll have to toggle your preference for reduced motion according to your user agent: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences
http://localhost:3000/demos/navigation.html
When you prefer reduced motion, the nav should be static.
When you do not prefer reduced motion, the nav should be sticky with animations to scroll in and out of view on page scroll (current behaviour all the time on https://www.mozilla.org/en-US/).
ℹ️ I have a fix for this specifically in bedrock: https://github.com/mozilla/bedrock/pull/10592
Do we want to merge that fix for now and save this until we can fully backport the bedrock nav …
=> Remove sticky nav for reduced motion (fixes #733)

CHANGELOG.md, package-lock.json, package.json, src/assets/sass/protocol/components/logos/_logo-product-relay.scss, src/assets/sass/protocol/components/logos/_wordmark-product-relay.scss, src/assets/sass/protocol/protocol-components.scss, src/pages/demos/logo.hbs, src/patterns/atoms/logo/logo.hbs, src/patterns/atoms/logo/wordmark.hbs
Adds logo and wordmark components for Firefox Relay after [Protocol Assets update](https://github.com/mozilla/protocol-assets/pull/80).
https://github.com/mozilla/protocol/issues/738
http://localhost:3000/demos/logo.html
=> Add Firefox Relay logos and wordmarks (fixes #738)

src/patterns/organisms/split/split.hbs
Noticed a mistake in the Split notes. The body width class goes on the outer container, not the body container (because grid). Just a doc fix, doesn't need to go in the changelog.
http://localhost:3000/patterns/organisms/split.html
=> Correct Split docs, body width class goes on the container

CHANGELOG.md, src/assets/sass/protocol/components/_breadcrumb.scss, src/assets/sass/protocol/protocol-components.scss, src/patterns/molecules/breadcrumb/breadcrumb.hbs
Created a new breadcrumb component which will be initially used in theVPN Resource Center, but will most likely be used in other areas on mozilla.org. 
Start your local server and navigate to http://localhost:3000/patterns/molecules/breadcrumb.html# and compare to current Figma [design](https://www.figma.com/file/xo5JhiQIlpGWkb9lgh0ccZ/VPN-Resource-Guide?node-id=16%3A256)
Short text on mobile sizing:
=> Create new breadcrumb component

CHANGELOG.md, src/assets/sass/demos/theme-firefox.scss, src/assets/sass/demos/theme-mozilla.scss, src/assets/sass/protocol/base/elements/_quotes.scss, src/assets/sass/protocol/base/utilities/_backgrounds.scss, src/assets/sass/protocol/components/_breadcrumb.scss, src/assets/sass/protocol/components/_call-out.scss, src/assets/sass/protocol/components/_feature-card.scss, src/assets/sass/protocol/components/_hero.scss, src/assets/sass/protocol/components/_picto-card.scss, src/assets/sass/protocol/components/forms/_form.scss, src/assets/sass/protocol/includes/_themes.scss, src/assets/sass/protocol/includes/forms/_lib.scss, src/pages/demos/theme-firefox.hbs, src/pages/demos/theme-mozilla.hbs, src/pages/docs/contributing.md, src/pages/fundamentals/themes.md
Adds a tertiary "accent" background color to the Firefox and Mozilla themes. I'm not sure if "accent" is actually the best name for this, happy to discuss alternatives.
https://demo1--mozilla-protocol.netlify.app/demos/theme-firefox.html
https://demo1--mozilla-protocol.netlify.app/demos/theme-mozilla.html
=> Add tertiary theme color, rename alt to secondary

CHANGELOG.md, src/assets/sass/protocol/components/_split.scss
A Split component with both reversed layout *and* overflowing media allows the media to overlap the content. The layout is reversed but when the image has no max-width, it's naturally left-aligned and expands to the right, often covering some of the text.
Floating the image to the right in this scenario aligns it to the right and lets it overflow to the left (or flippity-floppity in RTL).
See it in action on http://localhost:3000/demos/split-visual.html in the fifth example down.
=> Fix image overlapping content in a reversed Split with media overflow

CHANGELOG.md, package.json, src/assets/package/README.md, src/assets/package/package.json
This release includes the new breadcrumb component, new tertiary theme colors, and renames "alt" theme colors to "secondary" (which makes it a breaking change and hence a major version).
=> Bump version to 16.0.0

CHANGELOG.md, src/assets/js/protocol/protocol-utils.js
Adds a more robust polyfill (particularly `mozMatchesSelector`) to catch more e.matches errors and avoid overly noisy Sentry reporting.
https://github.com/mozilla/protocol/issues/736
https://sentry.prod.mozaws.net/operations/bedrock-prod/issues/9874490/tags/
Test on browserstack
Win 7 + Firefox 30 (most frequent tags in this error)
Win 10 + IE 8
Live site should show `.matches` error in console on an older browser: https://protocol.mozilla.org/patterns/molecules/details.html
Local site should show no error with same browser: http://localhost:3000/patterns/molecules/details.html
=> Add more robust polyfill (fixes #736)

bin/build.sh, package.json
In #746 I neglected that we use a separate systems for deploying stage/prod to how we build demos. This should hopefully fix: https://gitlab.com/mozmeao/protocol/-/pipelines/429718118/failures
#746
=> Add build command for deploying the docs (Issue #746)

CHANGELOG.md, src/assets/js/protocol/protocol-modal.js
Adds a small delay before calling `modal.focus()` when opening the Modal component.
- ~[ ] I have documented this change in the design system~.
#749
The bug is hard to reproduce on the Protocol demo page below, because I'm assuming it's a less intensive page to animate? You can reproduce the bug in the www.mozilla.org links in the attached issue.
I tested locally in bedrock that this fix works (feel free to do the same in review).
http://localhost:3000/patterns/organisms/modal.html
=> Fix keyboard focus capture on modal open animation (Fixes #749)

src/patterns/templates/content-container/content-container.hbs
The Content Containers page had a broken link, I fixed it
- go to http://localhost:3000/patterns/templates/content-container.html
- Scroll down under `Notes` header where it says "See the demo for examples of these." and test the link
=> Fixed broken link in Content Containers page

CHANGELOG.md, package.json
I'm not sure this technically makes any difference to our generated code, since we're manually creating both minified and non-minified JS files, but we should probably still set`--mode production` explicitly whenever we build the NPM package.
N/A
=> Make sure to build package using production mode

components/download-button/download-button--secondary.html, components/download-button/download-button.config.yml, components/download-button/download-button.html, components/download-button/readme.md
Migrate download button.
todo: once navigation is migrated, add link in Readme to navigation component
https://github.com/mozilla/protocol/issues/759
http://localhost:3000/components/detail/download-button--default
http://localhost:3000/components/detail/download-button--secondary
to compare with: https://protocol.mozilla.org/patterns/molecules/download-button.html
=> Migrate download button

CHANGELOG.md, theme/views/partials/header.nunj, theme/views/partials/navigation/navigation.nunj
Some areas in the menu bar lacked accessibility, notably a lack of an `alt` for the Github icon and a lack of a `role` for the nav toggle. Just patched that up!
There are still some accessibility issues that should be patched up, but it's not easy for us to pull that since they're coded within Fractal's codebase and dependencies, notably:
- The nav headers are defaulted to be `h3` but since there is no `h2` in the DOM all the time (depending on which page you're viewing), the hierarchy isn't very optimal
- The `iframe` tag isn't supposed to have a `title` attribute, mainly seen in the preview pages
Before this PR, accessibility was at 80% in Lighthouse, now it's at 98%:
I used MacOS' VoiceOver tool to see if it went through the menu's DOM reading correctly …
=> Added accessible attributes to menu bar (fixes #815)

CHANGELOG.md, assets/sass/protocol/components/logos/_logo.scss, assets/sass/protocol/components/logos/_wordmark.scss, components/branding/logo/logo.config.yml, components/branding/logo/logo.html, components/branding/logo/readme.md, components/branding/wordmark/readme.md, components/branding/wordmark/wordmark.config.yml, components/branding/wordmark/wordmark.html
Adds optional layout classes to the Logo and Wordmark components so they can be centered. We've been needing to do a local override to center logos when needed, hanging it on a class simplifies things and makes it more portable.
#718 
http://localhost:3000/components/detail/logo
http://localhost:3000/components/detail/wordmark
=> Add centering classes for Logo and Wordmark [fix #718]

CHANGELOG.md, theme/index.js
The 'Built on' date at the bottom of the sidebar uses the US-only date
format of MM/DD/YYYY.  This date format is ambiguous and is incorrect
for most of the world.
Fix this by replacing the month with its short name.
eg. `10/25/2022` becomes `Oct 25, 2022`.
=> Switch from US-only MM/DD/YYYY date format to the unambiguous 'MMM DD, YYYY'

assets/sass/protocol/base/elements/_links.scss, assets/sass/protocol/base/elements/_tables.scss, assets/sass/protocol/components/_menu-list.scss, assets/sass/protocol/components/_menu.scss, assets/sass/protocol/components/_modal.scss, assets/sass/protocol/components/_navigation.scss, assets/sass/protocol/components/_sidebar-menu.scss, components/split/split.config.yml, docs/03-contributing/03-css-guide.md, theme/assets/sass/components/_browser.scss, theme/assets/sass/components/_prose.scss, theme/assets/sass/components/_status.scss, theme/assets/sass/components/_tokens.scss
Fixes a minor regression from https://github.com/mozilla/protocol/pull/820. That changed rgba() colors to rgb() but used an invalid form of the CSS Colors 4 notation, mixing a slash for the alpha with a comma separated values for the color channels. The slash is only for space-separated syntax, and mixing slashes and commas doesn't work so the browser was ignoring those colors.
Furthermore, including an alpha channel in an rgb() color is only in Colors 4 and older browsers don't support it, so we should stick with rgba() for transparency for now. 
This changes all those invalid colors to comma-separated rgba() values.
Also fixes a param name in the Split component and the class name for the status dots.
=> Fix rgb color notation

CHANGELOG.md, components/forms/01-input/input.config.yml, components/forms/01-input/input.html
Removes `aria-disabled` from disabled input docs notes and HTML. It is not applicable for the use case we are demonstrating. `disabled` attribute only is what we want.
https://github.com/mozilla/protocol/issues/823
`npm run webpack-docs`
(in another terminal tab, same path) `npm start`
http://localhost:3000/components/detail/input--disabled
=> Remove aria-disabled from disabled input docs and example (fixes #823)

CHANGELOG.md, assets/js/protocol/protocol-modal.js
Fixes an a11y issue with the modal component by ensuring `focus()` is moved to the modal after the CSS fade in animation completes.
https://github.com/mozilla/protocol/issues/829
http://localhost:3000/components/detail/modal
=> Ensure focus is moved to modal after animation completes (Fixes #829)

netlify.toml
Updated netlfiy redirects from older drizzle URLs to the updated URLs for the fractal build
#812
You can look at [demo2](https://demo2--mozilla-protocol.netlify.app/) to test this change:
**example**: https://demo2--mozilla-protocol.netlify.app/patterns/organisms/billboard -> https://demo2--mozilla-protocol.netlify.app/components/detail/billboard
This will also work with or without a trailing `.html` on the url
=> Update netlify.toml with redirects from old drizzle urls

CHANGELOG.md, assets/sass/protocol/components/_notification-bar.scss
Related to issue #848, @maureenlholland and I spoke about how either increasing the `font-size` or  changing the `color` of the text in the notification bar would be slightly better for visual accessibility.
In the issue, I tested changes by:
- Increasing `font-size` to `16px`, and
- Changing `color` to `#000000`
Both seemed to be viable options for visual clarify on the component. However, a change in one of the notification bars would usually mean a change to the rest for sake of consistency. The increase in `font-size`, most notably on the success notification bar in the WNPs, seemed to jumble the order of the page's content hierarchy by just a bit. 
So instead of going with increasing `font-size` we opted to select to just change `color` to `#000000` for all notification bars. Not a …
=> Darkened notification bar font color

CHANGELOG.md, package.json
Adds missing browser list targets in `package.json` to make sure we're bundling JS in a compatible way with older IE browsers.
#861
I matched our browserlist targets in bedrock for parity: https://github.com/mozilla/bedrock/blob/main/package.json#L80-L83
=> Fix syntax error in legacy IE when compiling JS (Fixes #861)

CHANGELOG.md, assets/js/protocol/protocol-footer.js, assets/js/protocol/protocol-menu.js, assets/js/protocol/protocol-navigation.js
`MediaQueryList.addListener()` is deprecated and we should be replacing it with a more supported alternative, which is `EventTarget.addEventListener()`. 
Check this [compatibility list](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#browser_compatibility) (`MediaQueryList` inherits `EventTarget`) for the browser versions were keeping the fall back for (i.e. < Safari 14)
**Things to note:**
I'm using a `change` event to detect there has been a resize, and I got that from reading this in MDN: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/change_event
However, it should be noted that this event isn't listed in MDN's event references page: https://developer.mozilla.org/en-US/docs/Web/Events . I'll be filing an issue for this. …
=> Move from depracated `addListener` to `addEventListener` function

CHANGELOG.md, assets/sass/protocol/components/_split.scss
Remove default mobile padding on nospace split component (backported to bedrock)
Related to a bedrock issue & PR:
https://github.com/mozilla/bedrock/issues/11457
https://github.com/mozilla/bedrock/pull/11512#issuecomment-1104545527
#779
=> Remove default mobile padding on nospace split component

CHANGELOG.md, assets/sass/protocol/components/_split.scss
Removed the min-width on `.mzp-c-split-container` to prevent overflow on very small viewports - I tried to see if it broke anything but it seemed ok on my testing
#843 
- `npm run webpack`
- `npm run start`
- http://localhost:3000/components/detail/split
=> remove split min-width to prevent overflow on small viewports

CHANGELOG.md, assets/js/protocol/navigation.js, assets/js/protocol/supports.js
Moves the `aria-expanded` attribute to the `mzp-c-navigation-menu-button` instead of the menu items as explained in #847. Also removes the aria-expanded attribute on desktop since the element is not displayed, so firefox no longer includes it in the accessibility tree.
#847 
You can test this by running a local server and navigating to this page: http://localhost:3000/components/preview/navigation--default and using the inspector to view the element and make sure that the aria-expanded role is toggling correctly.
=> Update aria roles on mzp navigation

CHANGELOG.md, README.md, assets/package/README.md, assets/package/package.json, package-lock.json, package.json
Once this is merged, I'll tag a new release and add the following migration notes:
- Protocol JS components are now published in [UMD format](https://github.com/umdjs/umd) for easier consumption. They can now be imported directly using common build tools such as Webpack (see the docs), but are still available as a global variable for sites that need it. There's no longer a global `window.Mzp.*` name space however, so in your code `window.Mzp.Notification` should now become `window.MzpNotification` (as an example).
- We no longer publish pre-minified CSS and JS files in the NPM package. If you want minified assets, then it is now your responsibility to take care of that in your site's build process.
=> Bump protocol to v17.0.0

.eslintrc.js, CHANGELOG.md, assets/js/protocol/details.js, assets/js/protocol/footer.js, assets/js/protocol/menu.js, assets/js/protocol/navigation.js, components/details-component/details-component--custom.readme.md, components/details-component/details-component.html, components/details-component/readme.md, components/footer/01-footer/readme.md, components/language-switcher/readme.md, components/modal/readme.md, components/navigation/01-navigation/readme.md, components/navigation/02-menu/readme.md, components/newsletter/readme.md, components/notification-bar/notification-bar--scripted.readme.md, components/sidebar-menu/readme.md, components/sticky-promo/readme.md
Updates `MzpDetails` component so we have to explicitly initialize it after importing.
Updates components that have dependencies to make sure they exist on the global (`window`) object.
#879
Details component should still initialize as expected: http://localhost:3000/components/detail/details-component--default
=> MzpDetails component should be explicitly initialized (Fixes #879)

CHANGELOG.md, assets/sass/protocol/includes/themes/_firefox.scss
Protocol v18 had an incorrect value for `test-body-lg` variable in the firefox theme.
- [ x] I have documented this change in the design system.
- [ x] I have recorded this change in `CHANGELOG.md`.
`text-body-lg` should be 1.125rem instead of 1.1rem
=> Fix incorrect rem value

CHANGELOG.md, assets/sass/protocol/base/utilities/_titles.scss, docs/01-fundamentals/03-typography.md, docs/02-usage/02-framework.md
Add `mzp-u-centered` utility class.
Documents existing title utility classes.
#897
http://localhost:3000/docs/usage/framework
=> Add CSS utility class for centered text and document existing title utility classes (Fixes #897)

.eslintrc.js, CHANGELOG.md, assets/js/protocol/newsletter.js, assets/sass/protocol/base/elements/_forms.scss, assets/sass/protocol/components/_newsletter-form.scss, components/forms/02-select/select.config.yml, components/newsletter/newsletter--errors.html, components/newsletter/newsletter--success.html, components/newsletter/newsletter.config.yml, components/newsletter/newsletter.html, components/newsletter/readme.md, package-lock.json, package.json, tests/karma.conf.js, tests/unit/newsletter.js
This PR ports the JS code (and tests) from bedrock that handles newsletter form submissions.
This will help provide Mozilla websites with an up to date example of how to handle newsletter submissions that post directly to Basket, and will act as a replacement for https://github.com/mozilla/basket-example.
I also fixed a couple of other pesky long time bugs, like how small `<legend>` elements were rendered in Zilla Slab, making them hard to read.
#839
- http://localhost:3000/components/detail/newsletter--default
- http://localhost:3000/components/detail/newsletter--errors
- http://localhost:3000/components/detail/newsletter--success
=> Port basket newsletter JS to Protocol (Fixes #839)

CHANGELOG.md, assets/js/protocol/lang-switcher.js
Add a link to a related GitHub issue if applicable.
Not applicable.
Enter helpful notes for whoever code reviews this change.
Just a typo at `lang-switcher.js` comment, line 14.
=> Fix typo at lang-switcher.js comment

CHANGELOG.md, assets/sass/protocol/components/_button.scss
Explicitly sets `text-align: center;` for `.mzp-c-button` to compensate for button-styled links inheriting their alignment from their parent. This only really manifests when a button-style link is set to the full width of its container, but that does happen sometimes.
#826
=> Center-align button text [fix #826]

theme/views/partials/head.nunj
The Fractal base theme (Mandelbrot) has a hardcoded MIME type of `image/ico` in the head but we're using a PNG. We could, of course, just make a .ico file but we can also update the MIME type by overriding the base theme.
#911
=> Fix favicon mime type [fix #911]

CHANGELOG.md, assets/js/protocol/newsletter.js, components/newsletter/newsletter--errors.html, components/newsletter/newsletter--success.html, components/newsletter/newsletter.html, tests/unit/newsletter.js
The email marketing team have asked to remove the format option in the Newsletter component, as text based email are not supported by Braze (our new vendor).
https://github.com/mozilla/protocol/issues/926
=> Remove `format` option in Newsletter form

CHANGELOG.md, assets/sass/protocol/components/logos/_wordmark-product-klar.scss, assets/sass/protocol/protocol-components.scss, components/branding/wordmark/wordmark--products.html, components/branding/wordmark/wordmark--products.readme.md
We do not have a CSS class defined for Firefox Klar wordmark to be used for German locales in Bedrock. Instead, we've been using the English Firefox Focus wordmark. This PR adds that classname so it can be used (with a `{% if LANG=='de' %}` conditional.
i.e. (example used from @janbrasna's [PR in Bedrock](https://github.com/mozilla/bedrock/pull/14490/files#diff-f97847d5549ff9ef28dc0eabf97fe4f7b7a13d41a355fa1c7d8537c967d7604aR60):
```
<div class="mzp-c-wordmark mzp-t-wordmark-md {% if LANG=='de' %} mzp-t-product-klar {% else %}mzp-t-product-focus{% endif %}">{{ ftl('mobile-focus-firefox-focus') }}</div>
```
>[!NOTE]
> I didn't need to add a new logo component to support Klar since it's just Firefox Focus in German, so it uses the same logo.
Fixes …
=> Add Firefox Klar wordmark

assets/sass/protocol/includes/_tokens.scss, package-lock.json, package.json, theme/assets/sass/preview.scss, theme/assets/sass/theme.scss, webpack.package.static.config.js
Replaces https://github.com/mozilla/protocol/pull/995 due to some breaking changes in sass-loader 15.0
N/A
Please try building both the package and the docs locally to make sure everything still seems to work ok.
=> Update sass-loader to @16.0.3

README.md, docs/index.md, theme/views/partials/head.nunj
Adds current npm version and link to docs homepage.
Also adds meaningful links to repo readme badges, to link somewhere instead of the badge img itself.
As a bonus also fixes homepage title repeating itself…
Fixes #230
https://add-package-details--mzp-dev.netlify.app/
=> Add package details to docs

.github/workflows/docs-prod.yml
Pushes the tag/sha used for creating a Release to `prod` branch for Netlify to pick it up, building and publishing the production site.
This aims to do no lint/tests, as that all should have been sorted out merging into main, and when the Release author selects the commit~ish for releasing/tagging, they ought to have verified everything a-ok in staging and pipeline already.
If a changeset failing to build is pushed, nothing really happens as Netlify deployment will just fail the build but still keep the previous stable deployment available so until addressed, the previous version will be served.
Pushes are ff-only otherwise rejected so are foolproof, no destructive operation can happen.
Failures as releasing older versions than already published etc. are not skipped silently, but visibly …
=> Add workflow to publish docs on release

CHANGELOG.md, assets/sass/protocol/components/_modal.scss
Sets the cursor on the actual button element to avoid any UA defaults overriding it.
Resolves #955
https://fix-modal-close-pointer--mzp-dev.netlify.app/components/detail/modal
=> Fix modal "X" close cursor affordance

CHANGELOG.md, assets/sass/protocol/base/elements/_details.scss
Details _element_ gets styled very close to Details _component_ with many of the enhancements, just the hover affordance is missing for this plan HTML5 use case. This sets the cursor to pointer, as the full component does.
Resolves #948
https://patch-2--mzp-dev.netlify.app/components/detail/details
1. I have not fenced this behind any `@supports not (-ms-ime-align: auto)` of sorts for things like IE that don't provide the functionality as that adds extra cruft (and [false positives](https://github.com/mozilla/protocol/issues/948#issuecomment-2218321222)) for not much benefit, when MzpDetails actually provides a polyfill for such browsers.
2. I have opted for a plain extra declaration instead of the `@summary` mixin (which gets …
=> Add pointer to ‹details› element ‹summary›

CHANGELOG.md, assets/sass/protocol/base/elements/_titles.scss
> ![css-ui_css-text-wrap-balance](https://developer.chrome.com/static/docs/css-ui/css-text-wrap-balance/image/the-previous-exaples-are-c9809697f2f6a_856.png)
https://caniuse.com/css-text-wrap-balance is pretty well supported now with no real downside, known bugs or performance issues documented.
Resolves #910
Safari 16 vs. 17.5+
Firefox 115 (ESR) vs. 122+
PR: https://preview--mzp-dev.netlify.app/components/detail/headings
_(before:)_
_(after:)_
=> Add `text-wrap: balance` to all headings

CHANGELOG.md, assets/package/README.md, assets/package/package.json, package-lock.json, package.json
This version includes the switch to Mozilla Headline and Text.
=> Publish 20.0.0

CHANGELOG.md, assets/package/README.md, assets/package/package.json, assets/sass/protocol/components/_footer.scss, assets/sass/protocol/components/_navigation.scss, package-lock.json, package.json
Update protocol-assets and publish V21
https://github.com/mozilla/protocol-assets/issues/100
- http://localhost:3000/components/detail/footer
- http://localhost:3000/components/detail/navigation--default
- http://localhost:3000/components/detail/navigation--firefox
=> Update protocol-assets and publish V21

CHANGELOG.md, assets/sass/protocol/components/_breadcrumb.scss, components/breadcrumb/breadcrumb.html
- Updates the look of breadcrumbs to match mozilla/bedrock#15751
- Restricts max-width of breadcrumbs to match other site content
---
Fix #1036
Fix #933
I added some other test cases to help check wrapping on smaller screen sizes:
http://localhost:3000/components/detail/breadcrumb
The styles are intended to match http://www.mozilla.org/en-US/products/monitor/what-is-a-data-broker/ so I used dev tools to apply the update locally and compare.
=> Update breadcrumb component (Fix #1036, Fix #933)

CHANGELOG.md, assets/js/protocol/navigation.js
Adds forgotten `typeof` to make sure the support object is available.
Fixes #1085
https://github.com/mozmeao/springfield/issues/380
=> Fix typeof check for MzpSupports in navigation
